trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'stage_1'
    displayName: 'Stage 1'
    jobs:
      - job: 'job_1'
        displayName: 'Job 1'
        steps:
          - bash: echo "##vso[task.setvariable variable=my_var;isOutput=true]cat"
            name: 'output_var'

      - job: 'job_2'
        displayName: 'Job 2'
        steps:
          - bash: echo "##vso[task.setvariable variable=my_var;isOutput=true]dog"
            name: 'output_var'

  - stage: 'stage_2'
    displayName: 'Stage 2'
    dependsOn: 'stage_1'
    condition: |
      and(
        succeeded(),
        containsValue(dependencies.stage_1.outputs['*.output_var.my_var'], 'cat')
      )
    jobs:
      - job: 'show_var_value'
        displayName: 'Show variable values from last stage'
        variables:
          var_job1: $[ stageDependencies.stage_1.job_1.outputs['output_var.my_var'] ]
          var_job2: $[ stageDependencies.stage_1.job_2.outputs['output_var.my_var'] ]
          all_vars: $[ stageDependencies.stage_1.*.outputs['output_var.my_var'] ]
        steps:
          - bash: |
              echo "stage_1.job_1.output_var.my_var: $(var_job1)"
              echo "stage_1.job_2.output_var.my_var: $(var_job2)"
              echo "stage_1.*.output_var.my_var: $(all_vars)"
